### PR TITLE
Add matching for reference links

### PR DESCRIPTION
**Pull request by luisorbaiceta**

### CODE REVIEW

**Comment by luisorbaiceta** [comment]
@jsumners this solves the issue. I'm leaving this as a draft because I want to check all the edge cases

**Comment by luisorbaiceta** [comment]
In fact, these covers more link cases so we can simplify the regexes a lot

**Review by jsumners — APPROVED** [review]
Looks good to me.

I was trying to keep the expressions easier to read. But whatever gets us to ship is cool with me.

**Comment by luisorbaiceta** [comment]
I will leave it as is, simplifying regexes could lead to some backwards compatibility issues with previous versions.

**Comment by jsumners** [comment]
> I will leave it as is, simplifying regexes could lead to some backwards compatibility issues with previous versions.

Ship it.
giphy

**Comment by luisorbaiceta** [comment]
> Ship it. giphy

Seems that I don't have write access @mcollina

**Pull request merged**
