### PR TITLE
chore(organisations): add ydh nhsft logo

### PR DESCRIPTION
**Pull request by Fdawgs**
#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by lmammino** [comment]
hey @Fdawgs 

Are you sure the logo is properly placed into the canvas?

Screenshot 2021-02-14 at 10 00 25

I suspect it will have a lot of whitespace around (and the actual logo be very small) once rendered in the website...

**Comment by lmammino** [comment]
I did actually run the build and I can confirm my suspicion. Check out the following screenshots to see what I mean:

## Home page

Screenshot 2021-02-14 at 10 02 46


## Organisations page


Screenshot 2021-02-14 at 10 02 58

You should use an SVG editor tool and scale up the actual graphic to fill all the available canvas.

**Review by lmammino — CHANGES_REQUESTED** [review]
As per comments above, this needs some changes otherwise the logo won't display nicely on the website...

**Comment by Fdawgs** [comment]
Thanks @lmammino! I'll resolve it first thing Monday when I'm back in work.

**Comment by lmammino** [comment]
Happy to help if more help is needed :)

**Comment by Fdawgs** [comment]
Hi @lmammino, I've reduced the viewbox size to match the logo size.

I can't tell if it's working or not from my end as the images et al don't load when loading up a local instance of the site.

Capture

**Comment by lmammino** [comment]
Looks great now!

Screenshot 2021-02-16 at 09 38 48


Screenshot 2021-02-16 at 09 38 56

**Review by lmammino — APPROVED** [review]

**Comment by Fdawgs** [comment]
@lmammino Thanks for all the help!

**Comment by lmammino** [comment]
You are most welcome! Enjoy Fastify :)

**Pull request merged**
