### PR TITLE
Add SwissDev Jobs organization as user 

### PR DESCRIPTION
**Pull request by Vrq**
Adding SwissDev Jobs as a user of Fastify

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Vrq** [comment]
@lmammino would you mind having a look? :)

**Review by mcollina — APPROVED** [review]
lgtm

**Review by lmammino — APPROVED** [review]

**Comment by lmammino** [comment]
Awesome, thanks @Vrq !

**Comment by Vrq** [comment]
Thanks!

**Pull request merged**
