### PR TITLE
Fix/broken links

### LINKED ISSUE #71: Broken links in doc
How to test this:

```bash
npm run build
cd build
http-server # install this with npm i -g http-server or alternatively use `python -m SimpleHTTPServer 8080`

# in another shell
wget --spider -o wget.log -e robots=off --wait 1 -r -p --debug 'http://127.0.0.1:8080'
```

Links still broken:

```plain
Found 70 broken links.

http://127.0.0.1:8080/docs/v0.41.x/Factory.md
http://127.0.0.1:8080/docs/v0.40.x/Middlewares/'/docs/v0.40.x/Hooks'
http://127.0.0.1:8080/docs/v1.6.x/Middlewares/'/docs/v1.6.x/Request'
http://127.0.0.1:8080/docs/v0.39.x/Middlewares/'/docs/v0.39.x/Reply'
http://127.0.0.1:8080/docs/v1.4.x/Factory
http://127.0.0.1:8080/docs/latest/Middlewares/'/docs/latest/Hooks'
http://127.0.0.1:8080/docs/v1.2.x/Middlewares/'/docs/v1.2.x/Hooks'
http://127.0.0.1:8080/docs/v0.43.x/Factory.md
http://127.0.0.1:8080/docs/v1.0.x/Middlewares/'/docs/v1.0.x/Reply'
http://127.0.0.1:8080/docs/v1.1.x/Middlewares/'/docs/v1.1.x/Reply'
http://127.0.0.1:8080/docs/v0.39.x/Middlewares/'/docs/v0.39.x/Hooks'
http://127.0.0.1:8080/docs/v0.37.x/Middlewares/'/docs/v0.37.x/Reply'
http://127.0.0.1:8080/docs/v1.0.x/Middlewares/'/docs/v1.0.x/Request'
http://127.0.0.1:8080/docs/v1.0.x/Middlewares/'/docs/v1.0.x/Hooks'
http://127.0.0.1:8080/docs/v1.1.x/Middlewares/'/docs/v1.1.x/Hooks'
http://127.0.0.1:8080/docs/master/Factory.md
http://127.0.0.1:8080/docs/v0.38.x/Middlewares/'/docs/v0.38.x/Request'
http://127.0.0.1:8080/docs/v0.43.x/Middlewares/'/docs/v0.43.x/Reply'
http://127.0.0.1:8080/docs/v0.35.x/Middlewares/'/docs/v0.35.x/Request'
http://127.0.0.1:8080/docs/v0.37.x/Middlewares/'/docs/v0.37.x/Hooks'
http://127.0.0.1:8080/docs/v1.0.x/Factory
http://127.0.0.1:8080/docs/v0.35.x/Middlewares/'/docs/v0.35.x/Reply'
http://127.0.0.1:8080/docs/v1.3.x/Factory
http://127.0.0.1:8080/docs/v0.42.x/Middlewares/'/docs/v0.42.x/Request'
http://127.0.0.1:8080/docs/v0.43.x/Middlewares/'/docs/v0.43.x/Hooks'
http://127.0.0.1:8080/docs/v0.41.x/Middlewares/'/docs/v0.41.x/Reply'
http://127.0.0.1:8080/docs/v0.35.x/Middlewares/'/docs/v0.35.x/Hooks'
http://127.0.0.1:8080/docs/v1.1.x/Middlewares/'/docs/v1.1.x/Request'
http://127.0.0.1:8080/docs/latest/Factory
http://127.0.0.1:8080/docs/v1.6.x/Factory
http://127.0.0.1:8080/docs/v0.41.x/Middlewares/'/docs/v0.41.x/Hooks'
http://127.0.0.1:8080/docs/v1.2.x/Middlewares/'/docs/v1.2.x/Request'
http://127.0.0.1:8080/docs/v0.37.x/Middlewares/'/docs/v0.37.x/Request'
http://127.0.0.1:8080/docs/v0.38.x/Middlewares/'/docs/v0.38.x/Reply'
http://127.0.0.1:8080/docs/master/Logging/Factory.md
http://127.0.0.1:8080/docs/v0.41.x/Middlewares/'/docs/v0.41.x/Request'
http://127.0.0.1:8080/docs/master/Middlewares/'/docs/master/Reply'
http://127.0.0.1:8080/docs/v1.2.x/Factory
http://127.0.0.1:8080/docs/v1.3.x/Middlewares/'/docs/v1.3.x/Request'
http://127.0.0.1:8080/docs/latest/Middlewares/'/docs/latest/Request'
http://127.0.0.1:8080/docs/v0.38.x/Middlewares/'/docs/v0.38.x/Hooks'
http://127.0.0.1:8080/docs/v0.36.x/Middlewares/'/docs/v0.36.x/Reply'
http://127.0.0.1:8080/docs/v1.5.x/Middlewares/'/docs/v1.5.x/Reply'
http://127.0.0.1:8080/docs/v1.6.x/Middlewares/'/docs/v1.6.x/Reply'
http://127.0.0.1:8080/docs/master/Middlewares/'/docs/master/Hooks'
http://127.0.0.1:8080/docs/v1.4.x/Middlewares/'/docs/v1.4.x/Request'
http://127.0.0.1:8080/docs/v0.42.x/Middlewares/'/docs/v0.42.x/Reply'
http://127.0.0.1:8080/docs/v0.36.x/Middlewares/'/docs/v0.36.x/Hooks'
http://127.0.0.1:8080/docs/v1.5.x/Factory
http://127.0.0.1:8080/docs/v1.5.x/Middlewares/'/docs/v1.5.x/Hooks'
http://127.0.0.1:8080/docs/master/Server-Methods.md
http://127.0.0.1:8080/docs/v1.6.x/Middlewares/'/docs/v1.6.x/Hooks'
http://127.0.0.1:8080/docs/v1.3.x/Middlewares/'/docs/v1.3.x/Reply'
http://127.0.0.1:8080/docs/v1.4.x/Middlewares/'/docs/v1.4.x/Reply'
http://127.0.0.1:8080/docs/v0.43.x/Middlewares/'/docs/v0.43.x/Request'
http://127.0.0.1:8080/docs/v1.1.x/Factory
http://127.0.0.1:8080/docs/v0.40.x/Middlewares/'/docs/v0.40.x/Request'
http://127.0.0.1:8080/docs/v0.42.x/Middlewares/'/docs/v0.42.x/Hooks'
http://127.0.0.1:8080/docs/v0.40.x/Middlewares/'/docs/v0.40.x/Reply'
http://127.0.0.1:8080/docs/v0.40.x/Factory.md
http://127.0.0.1:8080/docs/v0.39.x/Middlewares/'/docs/v0.39.x/Request'
http://127.0.0.1:8080/docs/v1.3.x/Middlewares/'/docs/v1.3.x/Hooks'
http://127.0.0.1:8080/docs/v1.4.x/Middlewares/'/docs/v1.4.x/Hooks'
http://127.0.0.1:8080/docs/latest/Middlewares/'/docs/latest/Reply'
http://127.0.0.1:8080/docs/v1.2.x/Middlewares/'/docs/v1.2.x/Reply'
http://127.0.0.1:8080/docs/v1.5.x/Middlewares/'/docs/v1.5.x/Request'
http://127.0.0.1:8080/docs/master/Factory/Logging.md
http://127.0.0.1:8080/docs/v0.42.x/Factory.md
http://127.0.0.1:8080/docs/v0.36.x/Middlewares/'/docs/v0.36.x/Request'
http://127.0.0.1:8080/docs/master/Middlewares/'/docs/master/Request'
```

### PR DESCRIPTION
**Pull request by lmammino**
Fixes #71 

Changes proposed here closes most of the outstanding broken links. I am trying to figure out the remaining ones!

Remaining:

```
Found 20 broken links.

http://127.0.0.1:8080/docs/latest/Server-Methods.md
http://127.0.0.1:8080/docs/v0.42.x/Factory.md
http://127.0.0.1:8080/docs/v1.3.x/Factory
http://127.0.0.1:8080/docs/v1.4.x/Factory
http://127.0.0.1:8080/docs/v1.5.x/Factory
http://127.0.0.1:8080/docs/v0.41.x/Factory.md
http://127.0.0.1:8080/docs/v0.40.x/Factory.md
http://127.0.0.1:8080/docs/v1.1.x/Factory
http://127.0.0.1:8080/docs/v1.2.x/Factory
http://127.0.0.1:8080/docs/latest/Factory/Logging.md
http://127.0.0.1:8080/docs/latest/Logging/Factory.md
http://127.0.0.1:8080/docs/latest/Factory.md
http://127.0.0.1:8080/docs/master/Factory.md
http://127.0.0.1:8080/docs/v1.6.x/Factory
http://127.0.0.1:8080/docs/v1.7.x/Factory
http://127.0.0.1:8080/docs/master/Server-Methods.md
http://127.0.0.1:8080/docs/v0.43.x/Factory.md
http://127.0.0.1:8080/docs/master/Factory/Logging.md
http://127.0.0.1:8080/docs/master/Logging/Factory.md
http://127.0.0.1:8080/docs/v1.0.x/Factory
```

### CODE REVIEW

**Comment by lmammino** [comment]
After last commit:

```
Found 16 broken links.

http://127.0.0.1:8080/docs/v1.3.x/Factory
http://127.0.0.1:8080/docs/v1.4.x/Factory
http://127.0.0.1:8080/docs/v1.5.x/Factory
http://127.0.0.1:8080/docs/v0.41.x/Factory
http://127.0.0.1:8080/docs/v0.40.x/Factory
http://127.0.0.1:8080/docs/v1.1.x/Factory
http://127.0.0.1:8080/docs/v1.2.x/Factory
http://127.0.0.1:8080/docs/latest/Factory/Logging.md
http://127.0.0.1:8080/docs/latest/Logging/Factory.md
http://127.0.0.1:8080/docs/v1.6.x/Factory
http://127.0.0.1:8080/docs/v1.7.x/Factory
http://127.0.0.1:8080/docs/v0.43.x/Factory
http://127.0.0.1:8080/docs/v0.42.x/Factory
http://127.0.0.1:8080/docs/master/Factory/Logging.md
http://127.0.0.1:8080/docs/master/Logging/Factory.md
http://127.0.0.1:8080/docs/v1.0.x/Factory
```

**Comment by lmammino** [comment]
After last commit:

```
Found 4 broken links.

http://127.0.0.1:8080/docs/master/Logging/Factory.md
http://127.0.0.1:8080/docs/latest/Logging/Factory.md
http://127.0.0.1:8080/docs/master/Factory/Logging.md
http://127.0.0.1:8080/docs/latest/Factory/Logging.md
```

This is mergeable at this point. Those remaining links have to be cleaned up at source. I will submit a separate PR in the main repo in few hours!

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by lmammino** [comment]
🎉

**Comment by allevo** [comment]
Great! 👍

**Pull request merged**
