### PR TITLE
Fixed the counting of number of plugins

### PR DESCRIPTION
**Pull request by ehteshamdev0**
The "Explore Plugin" button on the homepage of the website shows "Explore 2 plugins" although it is supposed to be 36 (core) + 72 (community) = 108 plugins, because when earlier I explored the website it used to show the correct counts of the plugin.

After cloning and running the website I found out that the statement ( `data.ecosystem.plugins | length` ) to count the number of plugins
in **home.html** was only counting the types of plugin (core + community = 2) and not the actual plugins, as actual plugins were nested as "plugins>corePlugins>all_Core_Plugins" and "plugins>communityPlugins>all_Community_Plugins"

**Wrong count**\
wrong-count

I changed the statement to (`data.ecosystem.plugins.corePlugins | length + data.ecosystem.plugins.communityPlugins | length`) so that it can count the actual total plugins.

**Fixed count**

right-count

### CODE REVIEW

**Review by mcollina — CHANGES_REQUESTED** [review]
It’s really hard to see the changes in this PR, as they are all about changing the linting of the file.

Would you mind restoring the previous linting/code style? (You might have to disable prettier).

**Comment by ehteshamdev0** [comment]
I tried to disable prettier.\
If that doesn't seem to fix it I added a "TAG: Change here" comment so you can easily search for it in the "**home.html**" file.\
I hope that helps.

**Comment by mcollina** [comment]
I would recommend filing a new PR with the just the needed change.

You could fix this one by using git rebase and reverting the original change, but it’s probably not worth it.

**Comment by ehteshamdev0** [comment]
Sure I'll do it

**Comment by ehteshamdev0** [comment]
PR moved here : https://github.com/fastify/website/pull/131

**Pull request closed without merging**
