### PR TITLE
Improve TOC usability

### LINKED ISSUE #348: Scrolling the sidebar menu is difficult
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the issue has not already been raised

### Issue

When trying to scroll the left sidebar menu, it is not possible to reach the bottom with _also_ scrolling the overall page:

https://user-images.githubusercontent.com/321201/168860227-aee6e75f-a3e1-42e1-97a3-b6fff7d12c83.mp4

This made it really difficult to find the routing documentation that I knew was there. I kept trying to scroll the menu to see what I knew should be there, but couldn't reach it until I loaded a longer page and started scrolling that page.

### PR DESCRIPTION
**Pull request by luisorbaiceta**
As titled

closes #348

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by luisorbaiceta** [comment]
@jsumners

**Comment by luisorbaiceta** [comment]
@jsumners I think this should solve the problem

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]
image

**Pull request merged**
