### PR TITLE
Add Unhandled to the organisations list

### PR DESCRIPTION
**Pull request by msaglietto**
Hey guys .. Thanks for the make our life easier .. 
We been using fastify so we would like to be part of the organisations on the site if its possible

### CODE REVIEW

**Review by delvedor — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
LGTM

**Review by lmammino — APPROVED** [review]

**Comment by lmammino** [comment]
Not sure why test suite is not running anymore. Checking this manually to make sure the SVG is compliant

**Comment by lmammino** [comment]
All Good! Merging!

Thanks @msaglietto

**Pull request merged**
