### PR TITLE
fix a bunch of layout and style related stuff

### PR DESCRIPTION
**Pull request by GlenTiki**
I noticed there were some minor issues with content aligning with the header title, etc. I've just gone through it all and fixed what I can.

You can preview my changes at https://compassionate-colden-8e2445.netlify.com/

There was 3 other changes I made:

- "Acknowledgements" and "Hosted By" sections on the homepage now share a row
- NearForm capitalisation (nearForm -> NearForm)
- Add a reference to being an OpenJS project within the footer

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm. There is a lot more space.. I would add more companies to the "who is using Fastify".

**Comment by GlenTiki** [comment]
There is now 12 logos on the homepage, instead of 6.

**Comment by lmammino** [comment]
Hey @GlenTiki, sorry i totally missed this PR. There's a conflict on the home. Can you solve it and I'll get this merged? Thanks

**Comment by GlenTiki** [comment]
@lmammino So sorry I forgot about this. I've resolved the conflicts and rebased onto master. Preview is updated.

**Comment by lmammino** [comment]
Thanks a lot @GlenTiki! Merging now :)

**Pull request merged**
