### PR TITLE
Add MV Labs and RuneAudio as organizations using Fastify

### PR DESCRIPTION
**Pull request by ACXgit**
MV Labs is using Fastify to build APIs, API gateways and websites with isomorphic architecture.

RuneAudio is a free and open source software that turns embedded hardware into Hi-Fi music players, and it's using Fastify for the player backend in the upcoming v2.0.

Thank you for your work!

### CODE REVIEW

**Review by lmammino — APPROVED** [review]
Fantastic use cases, great to have you on board!

**Review by delvedor — APPROVED** [review]
❤️

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by cemremengu** [comment]
@ACXgit fantastic work!

**Pull request merged**
