### PR TITLE
Added authenticated GitHub API calls based on environment variables

### LINKED ISSUE #63: Rate limit to Github API
```
node src/scripts/downloadReleases.js fastify/fastify build-temp/releases v0.11.0

downloading releases into /home/circleci/fastify-website/build-temp/releases
{ StatusCodeError: 403 - {"message":"API rate limit exceeded for 52.90.181.163. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}
    at new StatusCodeError (/home/circleci/fastify-website/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/home/circleci/fastify-website/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/home/circleci/fastify-website/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/home/circleci/fastify-website/node_modules/request/request.js:188:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/home/circleci/fastify-website/node_modules/request/request.js:1171:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at IncomingMessage.<anonymous> (/home/circleci/fastify-website/node_modules/request/request.js:1091:12)
  name: 'StatusCodeError',
```

### PR DESCRIPTION
**Pull request by lmammino**
This should mitigate the issues with rate limiting (#63).

~~Still marked as Work In Progress as I want to spend a bit more time testing it~~

Closes #63 (for now, we can re-open if we bump into rate limits again)

### CODE REVIEW

**Comment by lmammino** [comment]
This has been tested and I already added the necessary env variables to CircleCI. As soon as this is merged the CI will be using authenticated API calls.

**Review by delvedor — APPROVED** [review]
Great work!!

**Comment by lmammino** [comment]
@delvedor, shall we wait for MOAR reviews or can we proceed with the merge?

**Comment by delvedor** [comment]
Maybe a review by @mcollina which raised the initial issue :)

**Review by mcollina — APPROVED** [review]
LGTM

**Pull request merged**
