### PR TITLE
feat(organisations):Add Webiny Headless Serverless  CMS

### PR DESCRIPTION
**Pull request by endymion1818**
- Add an optimized Webiny logo
- Add Webiny text, link & image references to organisations yaml file

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Review by mcollina — COMMENTED** [review]
lgtm

**Comment by mcollina** [comment]
The test are failing, there seem to be a problem with the image

**Comment by endymion1818** [comment]
@mcollina Oh, you need a `viewBox` attribute, it's stripped by default in SVGO, ok I'll update the PR.

**Review by jsumners — APPROVED** [review]

**Pull request merged**
