### PR TITLE
added radity to users. thanks for developing fastify.

### PR DESCRIPTION
**Pull request by oaksakal**
Added a new organisation. tested.
#### Checklist

- [ X ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included N/A
- [ ] documentation is changed or added N/A
- [ X ] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by delvedor — APPROVED** [review]
LGTM

**Review by Eomm — APPROVED** [review]
🎉

**Comment by lmammino** [comment]
having a look now, sorry for the delay :)

**Comment by lmammino** [comment]
Seems good :)

**Review by lmammino — APPROVED** [review]

**Pull request merged**
