### PR TITLE
Add entry and logo for ClearGlass

### PR DESCRIPTION
**Pull request by pushpak1300**
Clearlgass is using fastify.js for its backend microservice. It would be great to be listed in the list of organizations using fastify 😄

### CODE REVIEW

**Comment by mcollina** [comment]
@lmammino can you check why the build is failing?

**Review by Fdawgs — CHANGES_REQUESTED** [review]
Please add the organisation alphabetically to `organisations.yml`, not at the end.
See https://www.fastify.io/organisations/#how-to-be-featured

**Comment by pushpak1300** [comment]
Preview:  https://pushpak1300-website-7qpv-8080.githubpreview.dev/

**Review by Fdawgs — APPROVED** [review]

**Comment by lmammino** [comment]
Sorry for the delay. The build was fixed here: https://github.com/fastify/fastify/commit/647eda62772e3728eddbbef17898d28e2bd2699f#diff-6e498fbb74d36e22505f94fa2f083a9f3f3741aae2534c96e860d0daffb516e9 (thanks @Fdawgs!!!)

**Review by lmammino — APPROVED** [review]
Thanks @pushpak1300

**Pull request merged**
