### PR TITLE
fix: change link color to increase accessibility

### LINKED ISSUE #237: Decorate hyperlink <a> tags to make them stand out
## 🚀 Feature Proposal

Change links to a different color, or decorate them i.e. bold or underline.

## Motivation

This may be the result of my color blindness, but the links and text use colors that are too similar, meaning that links just blend in with the text.
This makes it easy for links to be missed when reading a page.

As an example, in the image below I can't tell from a glance that `more organisations using Fastify` is a link 😢 

Capture

### PR DESCRIPTION
**Pull request by Fdawgs**
Went for MDN's link colour as their site is quite accessible, though could also use the holy grail that is [gov.uk](https://www.gov.uk/)'s colour scheme as reference.

Closes #237 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
@lmammino how would @Fdawgs be able to generate a preview to screenshot and provide here?

**Comment by jsumners** [comment]
Might also want to run it through https://www.toptal.com/designers/colorfilter/ to find a universal-ish color.

**Comment by lmammino** [comment]
The easiest way to test your changes is to do `npm run start:dev`. It should open a browser window for you. Every time you change a file it should rebuild and refresh automatically (with some lag 😅)

Let me know if this helps or if you get stuck with something

**Comment by lmammino** [comment]
Screenshot 2021-02-17 at 08 56 37

Do you feel this is a good enough improvement?

**Comment by lmammino** [comment]
We can simulate color deficiencies with Chrome:

## Blurred vision

Screenshot 2021-02-17 at 09 01 30


## Pratanopia

Screenshot 2021-02-17 at 09 02 09


## Deuteranopia

Screenshot 2021-02-17 at 09 02 36


## Tritanopia

Screenshot 2021-02-17 at 09 03 02


## Achromatopsia

Screenshot 2021-02-17 at 09 03 28

--

All look quite good to me, except the last one... maybe we should always have the underline enabled for links...

**Comment by lmammino** [comment]
How do you feel about adding a:

```css
border-bottom: 1px dotted #00458b;
```

In links?

## Normal vision

Screenshot 2021-02-17 at 09 07 24

## Achromatopsia

Screenshot 2021-02-17 at 09 07 15


If we go for this approach we should probably remove the border in all the images inside a link:

```
a img, a svg {
  border-bottom: none;
}
```

**Comment by Fdawgs** [comment]
> 
> 
> The easiest way to test your changes is to do `npm run start:dev`. It should open a browser window for you. Every time you change a file it should rebuild and refresh automatically (with some lag 😅)
> 
> Let me know if this helps or if you get stuck with something

I do attempt to test the changes locally however the resources don't load 😞   :
Capture


The following errors are thrown in the console:

`The stylesheet http://127.0.0.1:8080/ was not loaded because its MIME type, “text/html”, is not “text/css”.`
`The script from “http://127.0.0.1:8080/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.`

Tested using both Edge 88.0.705.68 and Firefox 85.0.2

**Comment by Fdawgs** [comment]
> 
> 
> How do you feel about adding a:
> 
> ```css
> border-bottom: 1px dotted #00458b;
> ```

Looks good!

**Comment by mcollina** [comment]
+1

**Comment by jsumners** [comment]
> How do you feel about adding a:
> 
> ```css
> border-bottom: 1px dotted #00458b;
> ```
> 
> In links?

Dotted is the default style for `abbr` elements. I'd rather just not remove the default underline style from `a` elements.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — APPROVED** [review]
LGTM

**Review by lmammino — APPROVED** [review]

**Comment by lmammino** [comment]
Looks great, thanks @Fdawgs!

I had a quick navigation around various pages and the only doubt I have is about the navigation bar:

Screenshot 2021-02-18 at 17 58 46

Screenshot 2021-02-18 at 17 58 58

Screenshot 2021-02-18 at 17 59 10

I would suggest we remove the underline from there... thoughts?

**Comment by Fdawgs** [comment]
@lmammino I think that's a good idea as it is expected for nav bars to be composed of links anyway!

Updated with https://github.com/fastify/website/pull/238/commits/972c9cee1178b2c3baf36f984b63be62e4d91071

**Comment by lmammino** [comment]
Awesome, thanks @Fdawgs! Merging shortly

**Comment by lmammino** [comment]
It's live! 🥳

**Comment by Fdawgs** [comment]
Seems to have inadvertently changed the background-color of the active link in the table of contents:

Capture


Looks nice (to me at least). 🤷

**Pull request merged**
