### PR TITLE
Publishing on github pages

### PR DESCRIPTION
**Pull request by lmammino**
Part of #26

Publish the website on github pages using `gh-pages` (so that we can drop S3)

**Ready for review**

Todo:

- [x] Update README
- [x] Add `404.html` (clone of current `error.html`)

### CODE REVIEW

**Review by delvedor — COMMENTED** [review]
We should add `package-lock.json` to the gitgnore.

**Comment by lmammino** [comment]
@delvedor why?

**Comment by lmammino** [comment]
This is now Ready for review

**Review by mcollina — APPROVED** [review]
LGTM

**Pull request merged**
