### PR TITLE
Add social graph meta

### PR DESCRIPTION
**Pull request by darkgl0w**
Closes https://github.com/fastify/website/issues/15

Credits goes to @lmammino for the images ^^

Possible enhancements :
Currently the `og:url` meta tag point to fastify.io website (I am not very familiar with metalsmith but it should be possible to fill this meta tag with the url of the page that is effectively linked)

### CODE REVIEW

**Comment by lmammino** [comment]
This is brilliant, thanks so much! I added the full path in `og:url` :)

**Review by lmammino — APPROVED** [review]

**Comment by lmammino** [comment]
This seems to be working fine, thanks again @darkgl0w 


screenshot 2019-03-02 at 16 32 44

**Comment by lmammino** [comment]
Also: https://twitter.com/loige/status/1101883711182856193 :)

screenshot 2019-03-02 at 16 38 39

**Comment by jsumners** [comment]
🎉

**Pull request merged**
