### PR TITLE
add microsoft logo

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

(it took longer to find the svg logo than it did to open this pr 😂)

### CODE REVIEW

**Review by StarpTech — APPROVED** [review]
LGTM

**Review by delvedor — APPROVED** [review]
LGTM 🚀

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Eomm** [comment]
Does not worth add it in the home page too? 

(from mobile I see it only in the org page https://www.fastify.io/organisations/)

**Comment by delvedor** [comment]
@Eomm the home page contains a randomized subset of the orgs, it should change automatically every now and then :)
Am I right @lmammino?

**Comment by Eomm** [comment]
Mmmm looking the code you are right
https://www.github.com/fastify/website/tree/master/src%2Fwebsite%2Flayouts%2Fhome.html

My incognito returns always the same list.
Does it change for you?

**Comment by lmammino** [comment]
Hello guys, I can confirm the home page will randomize the logos and select a subset of them at every build. We can definitely change the logic if we want. It shouldn't be a big deal.

A simple idea might be to add an attribute like `pinned: true` in the list of logos and then make sure the pinned ones are always selected in the random subset. What do you think?

Anyway, I am thrilled to see the Microsoft logo here ❤️

**Comment by mcollina** [comment]
Let's go for pinned.

**Pull request merged**
