### PR TITLE
Incorrect folder for organisation logo

### PR DESCRIPTION
**Pull request by angrymouse**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by angrymouse** [comment]
We need to make check in CI for that

**Comment by angrymouse** [comment]
🤦🏿

**Comment by angrymouse** [comment]
What's wring with check of organisations.yml? (I just can't see snyk's logs)

**Comment by angrymouse** [comment]
Ok I have no idea fix my PR please 🥺

**Comment by mcollina** [comment]
What's the problem?

**Comment by angrymouse** [comment]
> What's the problem?

I put the logo of organisation in the wrong folder, but CI didn't tell me anything. And it even got into the master branch. So I noticed that there is no test for the organisations.yml file, and I wrote it. But it can't pass snyk tests (and I don't know why).

**Comment by mcollina** [comment]
don't worry about snyk.
The CI is failing :(.

https://app.circleci.com/pipelines/github/fastify/website/937/workflows/3c829e51-6c9c-46fa-9a9a-deba8e1f27fc/jobs/2753/parallel-runs/0/steps/0-103

something is wrong with your package.json.

**Comment by mcollina** [comment]
Start from a fresh branch and just move the file.

**Comment by angrymouse** [comment]
> don't worry about snyk. The CI is failing :(.
> 
> [app.circleci.com/pipelines/github/fastify/website/937/workflows/3c829e51-6c9c-46fa-9a9a-deba8e1f27fc/jobs/2753/parallel-runs/0/steps/0-103](https://app.circleci.com/pipelines/github/fastify/website/937/workflows/3c829e51-6c9c-46fa-9a9a-deba8e1f27fc/jobs/2753/parallel-runs/0/steps/0-103)
> 
> something is wrong with your package.json.

That's because I deleted package-lock hoping that will fix Snyk

**Comment by angrymouse** [comment]
> Start from a fresh branch and just move the file.

Okay, but we still need tests for organisations.yml

**Comment by angrymouse** [comment]
Btw I restored package-lock and CI passed

**Review by mcollina — APPROVED** [review]
lgtm

**Pull request merged**
