### PR TITLE
Refresh contributor section visual

### LINKED ISSUE #146: Contributors section: design improvement
## 🚀 Feature Proposal

Hello, I was playing a bit with SVG clip paths and I got some interesting results that can be used to make the  contributors section in the home page a little bit more lively.

This is just an experiment, so be brutal on your feedback. If you like it tough, I will submit a PR :)

## Example

Screen Shot 2020-01-14 at 10 24 24 AM

### PR DESCRIPTION
**Pull request by lmammino**
Applies changes as per screenshot below.

Closes #146 

Screenshot 2020-01-15 at 19 47 25

### CODE REVIEW

**Review by allevo — APPROVED** [review]
LGTM

**Review by jsumners — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
I would rotate the hexagon 90 degrees, as the node one is.

**Review by Eomm — APPROVED** [review]
I like it A LOT!

**Comment by lmammino** [comment]
Rotated:

Screen Shot 2020-01-16 at 10 01 13 AM

Funny backstory: I couldn't find any tool to rotate the points and I ended up writing a rotation function myself 🤦🏻‍♂️

```javascript
const rawPoints = '92.32051% 40%,93.79385% 43.1596%,94.69616% 46.52704%,95% 50%,94.69616% 53.47296%,93.79385% 56.8404%,92.32051% 60%,79.82051% 81.65064%,77.82089% 84.50639%,75.35575% 86.97152%,72.5% 88.97114%,69.3404% 90.44449%,65.97296% 91.34679%,62.5% 91.65064%,37.5% 91.65064%,34.02704% 91.34679%,30.6596% 90.44449%,27.5% 88.97114%,24.64425% 86.97152%,22.17911% 84.50639%,20.17949% 81.65064%,7.67949% 60%,6.20615% 56.8404%,5.30384% 53.47296%,5% 50%,5.30384% 46.52704%,6.20615% 43.1596%,7.67949% 40%,20.17949% 18.34936%,22.17911% 15.49361%,24.64425% 13.02848%,27.5% 11.02886%,30.6596% 9.55551%,34.02704% 8.65321%,37.5% 8.34936%,62.5% 8.34936%,65.97296% 8.65321%,69.3404% 9.55551%,72.5% 11.02886%,75.35575% 13.02848%,77.82089% 15.49361%,79.82051% 18.34936%'

const points = rawPoints.split(',').map((p) => p.replace(/%/g, '').split(' '))
const rot = 1.5708 // 90 in radians
const center = [50, 50]

function rotatePoints (points, rot, center) {
  return points.map(([x, y]) => [
    (center[0] + ((x - center[0]) * Math.cos(rot)) - ((y - center[1]) * Math.sin(rot))),
    (center[1] + ((x - center[0]) * Math.sin(rot)) + ((y - center[1]) * Math.cos(rot)))
  ])
}

const rotated = rotatePoints(points, rot, center)
const rotatedRawPoints = rotated.map(([x, y]) => `${x}% ${y}%`).join(',')
console.log(rotatedRawPoints)
```

Give me some thumbs up and I'll merge this 😃

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by lmammino** [comment]
Merged! Thank you all for the quick turnaround on providing feedback ❤️

**Pull request merged**
