### PR TITLE
added 2hire to organisations using fastify

### PR DESCRIPTION
**Pull request by mircoc**
Added [2hire.io](https://2hire.io/) logo.
We currently use v2.14 but we'll migrate soon to v3.
Thanks!

### CODE REVIEW

**Review by Eomm — APPROVED** [review]
💯

**Comment by lmammino** [comment]
I think the SVG viewbox is not proportionate in terms of whitespace. Could you please make it so that the logo graphic is taking all the horizontal space of the canvas?

**Comment by lmammino** [comment]
Why I am trying to say is to do some cropping like in the following image:

image

**Comment by mircoc** [comment]
> Why I am trying to say is to do some cropping like in the following image:
> 
Sorry, it should be better now...

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by lmammino** [comment]
Great, thanks for applying the changes @mircoc!

**Review by lmammino — APPROVED** [review]

**Pull request merged**
