### PR TITLE
Add Seznam.cz to organisations using fastify

### PR DESCRIPTION
**Pull request by jurca**
#### Checklist

- [x] run `npm run test` ~~and `npm run benchmark`~~
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by SerayaEryn — APPROVED** [review]

**Comment by VottusCode** [comment]
@jurca Hmm, interesting, so Seznam finally switched from Express? Or just partially, because IMA still uses Express afaik 🤔 
Nevertheless it's cool that bigger companies also switch to Fastify and are not in the dying Express ecosystem.

**Comment by jurca** [comment]
@VottusCode There are multiple solutions used server-side, both Fastify and Express are among them. It comes down to the project, preferences of the maintaining team and priorities. However, Fastify is becoming more popular these days at Seznam :grin: .

**Comment by VottusCode** [comment]
> @VottusCode There are multiple solutions used server-side, both Fastify and Express are among them. It comes down to the project, preferences of the maintaining team and priorities. However, Fastify is becoming more popular these days at Seznam 😁 .

That's cool! 👍 I hope that at some point you're gonna transfer to Fastify completely!

**Pull request merged**
