### PR TITLE
 Fix website build fail on wsl

### LINKED ISSUE #246: Running on Wsl
## 🐛 Bug Report

Development server doesn't start on wsl

## To Reproduce

image

After Running `npm install` and running `npm start:dev`

To start a dev server

## Expected behavior

Should start the development server

## Your Environment

- *node version*: v14.16.0
- *fastify version*: >=2.0.0
- *os*: Linux
- Wsl

### PR DESCRIPTION
**Pull request by veritem**
fix #246 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
Is the addition of package-lock the only change needed?

**Comment by veritem** [comment]
@mcollina  I'm still looking into the cause of this will push when I find something

**Comment by lmammino** [comment]
Hello @makuzaverite, thanks for your work on this.

Unfortunately in your PR you are reformatting all the files and it is quite hard to review what you have changed. Would you be able to either revert the style changes or at least post in a comment what are the new additions (or main changes) that you are proposing here? Maybe we can re-apply them in a clean new branch.

**Comment by lmammino** [comment]
Closed in favour of #263

**Pull request closed without merging**
