### PR TITLE
Revert Case Handling for all docs

### PR DESCRIPTION
**Pull request by luisorbaiceta**
Reverts #285 to just handle cases for index files. This is a quick fix till some proper logic is implemented as discussed with @climba03003 

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
Apparently there is a conflict, can you resolve?

**Comment by luisorbaiceta** [comment]
Everything is working as expected

**Comment by climba03003** [comment]
Thanks for the quick fix.

**Comment by jsumners** [comment]
This is fantastic! Love seeing this:

image

**Pull request merged**
