### PR TITLE
Add tests for ensuring Organisations SVGs have explicit width or height

### LINKED ISSUE #91: Organisations SVGs need explicit width or height
Nucleode logo is there but it displays with 0x0 pixels. I will fix this specific case manually and I will try to identify a way to avoid this from happening again before merging PRs.

CC: @mcollina @fox1t @cemremengu

### PR DESCRIPTION
**Pull request by lmammino**
Fixes #91 

Fixes Nucleode logo and add tests to avoid this issue from happening again.

At build time all the SVGs will be checked for compliance. If a PR has a non compliant SVG we should be able to spot that automatically in the PR branch and understand why.

screen shot 2018-09-22 at 10 48 14

I also updated the description in the organisations page to make explicit that we need to have image width or height and changed suggested image optimizer (as the previous one was actually removing width and height 😓)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
LGTM

**Review by cemremengu — APPROVED** [review]
Nice work!

**Review by allevo — APPROVED** [review]
LGTM!

**Comment by StarpTech** [comment]
@lmammino I think we should add a preprocess. [Why?](https://github.com/svg/svgo#why)

https://github.com/svg/svgo

I have very good experience with that tool.

**Comment by lmammino** [comment]
@StarpTech, good point, shall we create a metalsmith middleware for integrating that? do you want to have a go with this?

**Comment by StarpTech** [comment]
@lmammino yes I can investigate.

**Pull request merged**
