### PR TITLE
Add Jobs in JS to the list of Fastify users

### PR DESCRIPTION
**Pull request by michalmalota**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by Uzlopak** [comment]
For what do you use fastify? I checked your page, but it seems that you use nextjs and serverless stuff from vercel?

**Comment by michalmalota** [comment]
That's right, the website uses nextjs, but the [admin api](https://tools.jobsinjs.com/) is based on fastify.

**Review by RafaelGSS — APPROVED** [review]

**Review by Eomm — APPROVED** [review]

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mcollina** [comment]
@michalmalota this is failing our build:

```
😱  jobsinjs.svg: invalid SVG content, "viewBox" not defined in xmlns tag
```

https://app.circleci.com/pipelines/github/fastify/website/1663/workflows/778dfe47-ae0c-4654-aab8-c880e41ffdf3/jobs/3191

Can you fix it?

**Comment by michalmalota** [comment]
@mcollina Apologies, I did not realise viewBox is camelCase. Surprisingly, the test did not fail when I run it in Github Codespace.

PR with the fix https://github.com/fastify/website/pull/385

**Pull request merged**
