### PR TITLE
Added Heply organisation

### PR DESCRIPTION
**Pull request by SteroixDev**

### CODE REVIEW

**Review by delvedor — APPROVED** [review]
LGTM

Hello from Udine! 😄

**Comment by SteroixDev** [comment]
Hello! 
We are from Udine

**Comment by delvedor** [comment]
> We are from Udine

I saw! Me too ;)

**Comment by lmammino** [comment]
Awesome. I'll quickly test this as I see all the adobe comments are still in the SVG and I'd like to get rid of useless metadata :) Give me 10 minutes

**Comment by SteroixDev** [comment]
No problem!

Proceed with your tests 👍

**Review by lmammino — APPROVED** [review]

**Comment by lmammino** [comment]
All Done and LGTM :)

**Comment by lmammino** [comment]
Btw, I love your website :)

**Pull request merged**
