### PR TITLE
Support for Docs Reorganization

### PR DESCRIPTION
**Pull request by luisorbaiceta**
Add support for fastify/fastify#3474 

In order to add support for the docs reorganization, as described in this [comment](https://github.com/fastify/fastify/pull/3474#issuecomment-982943091), to support a [global index](https://github.com/fastify/fastify/blob/2a7a9260f74655f31e43ed7aae0ae2b3dbadf0f9/docs/index.md) in the documentation there are a few steps we need to follow prior to merging the work.

The desired behaviour is the following:

1. User lands the website
2. Clicks Documentation link
3. User lands the documentation page with [global docs index](https://github.com/fastify/fastify/blob/2a7a9260f74655f31e43ed7aae0ae2b3dbadf0f9/docs/index.md) displayed. (Right now there is an intermediate step where user enters a table of contents page that is already present in the docs as a side bar)

### Steps

To achieve this we need:
- [x] Remove [createVersionIndexFile](https://github.com/fastify/website/blob/944247a26dd331f34bb5dfaf240fdff34badc87f/src/scripts/processReleases.js#L210) method to prevent scripts from generating the table of contents page under the `/docs/${version}`.
- [x] Remove [createIndexFiles](https://github.com/fastify/website/blob/944247a26dd331f34bb5dfaf240fdff34badc87f/src/scripts/processReleases.js#L228) method to prevent script frm generating the version selection page under the `/docs` path.
- [x] Render `index` file with current docs template.
- [x] Add default behaviour for landing the docs (should display the `index`).
- [x] Add a Default index to previous versions (for backwards compatibility).
- [x] Check current routing to detect possible collisions.
- [x] Remove dangling templates and styles.

### Motivation

Simplify user experience to make it more intuitive to access docs and navigate the page. For that we are removing the docs version selection page under the `docs/` route and the table of contents under the `docs/${version}` route. Both pages' content are already present in the `docs/${version}/${doc}` page (as a sidebar and a breadcrumb).

#### Checklist

- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
Will this be backward compatible with the prior branches?

**Comment by luisorbaiceta** [comment]
> Will this be backward compatible with the prior branches?

Yes. We are just removing two unnecessary pages and doing some clean up

**Comment by jsumners** [comment]
> > Will this be backward compatible with the prior branches?
> 
> Yes. We are just removing two unnecessary pages and doing some clean up


2w4stw

**Comment by luisorbaiceta** [comment]
For previous versions that don't have a root level `docs/index.md` file, I will create a default page to mimic that role (I will take what your are currently purposing in `docs-reorg` @jsumners ).

**Comment by luisorbaiceta** [comment]
It would be super awesome to have access to a [build preview](https://alejandrocelaya.blog/2021/05/09/setting-up-a-preview-environment-for-your-client-side-apps-with-github-actions-and-github-pages/) for future contributions...

**Comment by luisorbaiceta** [comment]
I have added this as a default layout for index

image

**Review by jsumners — APPROVED** [review]
Looks good to me.

**Comment by jsumners** [comment]
To be clear @luisorbaiceta, we can merge this without any issue in generating the current website with the docs organized in their current flat structure?

**Comment by luisorbaiceta** [comment]
Yes 👌

**Comment by luisorbaiceta** [comment]
We still need to include #299

**Pull request merged**
