### PR TITLE
fix: good first issues api link

### LINKED ISSUE #345: Broken contributing/good first issues page
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have searched existing issues to ensure the bug has not already been reported

### Description

Open the good first issue page, it shows an error.

### Steps to Reproduce

Open the good first issue page, it shows an error.

### Expected Behavior

_No response_

### PR DESCRIPTION
**Pull request by simoneb**
Fixes #345 

I can't run this on Windows, can somebody test it's all working fine? I tested that the API url is correct and that it returns sensible data.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by luisorbaiceta** [comment]
Working fine on my end

**Comment by simoneb** [comment]
All the builds are broken, no idea really as the change is a very minor one 🤷

**Comment by luisorbaiceta** [comment]
Seems that your forks master branch is behind the fastify/website one

**Comment by simoneb** [comment]
> Seems that your forks master branch is behind the fastify/website one

I would be surprised if this was the case, what suggests that it is?

**Comment by mcollina** [comment]
I don't think the failure is relevant to this change.

**Comment by luisorbaiceta** [comment]
My guess is that a previous version of the website didn't support the current nested docs structure, thus processRealease.js script is failing

**Pull request closed without merging**
