### PR TITLE
add banner for openjs world

### PR DESCRIPTION
**Pull request by jorydotcom**
Adds a banner for the OpenJS World Event on June 2 per suggestion from @mcollina. 
Screen Shot 2021-05-24 at 11 07 33 AM

If that looks too funny, I've also added a link next to the OpenJS logo: 
Screen Shot 2021-05-24 at 11 08 58 AM

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by Fdawgs** [comment]
Viewing it at a higher resolution it looks a bit... off 😢 

image

**Comment by mcollina** [comment]
@jorydotcom could you fix this?

**Comment by lmammino** [comment]
Hello @jorydotcom! Sorry for chiming in only now. Just noticed this. And, of course, thanks for the lovely contribution! :)

I was thinking we could make this responsive if we split the background image from the text/logo part. Would you be able to provide the 2 layers in separate files?

If you could do that, I'd be more than happy to take on the remaining work and try to address this and make it look responsive :)

**Comment by jorydotcom** [comment]
@lmammino @mcollina I am so sorry, I tested on mobile but didn't even think about bigger screens 😬 I'll get the original files from the team and send a fix. Happy to take this down for now too if you'd like.

**Pull request merged**
