### PR TITLE
feat: add Quero Education to fastify organisations

### PR DESCRIPTION
**Pull request by RafaelGSS**
#### Checklist

- [X] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [X] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by RafaelGSS** [comment]
I'll adjust the viewBox content later :+1:

**Review by Eomm — APPROVED** [review]
🔝

**Review by lmammino — CHANGES_REQUESTED** [review]
hey @RafaelGSS, the CI is failing with the following error:

> 😱  quero-educacao.svg: invalid SVG content, "viewBox" not defined in xmlns tag

Could you please make sure that the SVF has a `viewBox` attribute as in the other pictures? 

EDIT:

> I'll adjust the viewBox content later 👍

Sorry, saw this one too late 😅

**Comment by lmammino** [comment]
Looks good, thanks @RafaelGSS!

**Review by lmammino — APPROVED** [review]

**Pull request merged**
