### PR TITLE
Resolve issue #298

### PR DESCRIPTION
**Pull request by jsumners**
This PR should resolve issue #298.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by jsumners** [comment]
@luisorbaiceta please take a look.

**Comment by luisorbaiceta** [comment]
it's not working, reference links don't get remapped

**Comment by jsumners** [comment]
The only reference links I have found in the current documentation, that should be build with the `latest` tag, are https://github.com/fastify/fastify/blob/1b49c5b698ad0727ce18efff852d8a703c67be94/docs/TypeScript.md?plain=1#L1232-L1258

My latest commit converts that to the following in the `v3.19.x` doc:

```
[Fastify]: /docs/v3.19.x/TypeScript#fastifyrawserver-rawrequest-rawreply-loggeropts-fastifyserveroptions-fastifyinstance
[RawServerGeneric]: /docs/v3.19.x/TypeScript#rawserver
[RawRequestGeneric]: /docs/v3.19.x/TypeScript#rawrequest
[RawReplyGeneric]: /docs/v3.19.x/TypeScript#rawreply
[LoggerGeneric]: /docs/v3.19.x/TypeScript#logger
[RawBodyGeneric]: /docs/v3.19.x/TypeScript#rawbody
[HTTPMethods]: /docs/v3.19.x/TypeScript#fastifyhttpmethods
[RawServerBase]: /docs/v3.19.x/TypeScript#fastifyrawserverbase
[RawServerDefault]: /docs/v3.19.x/TypeScript#fastifyrawserverdefault
[FastifyRequest]: /docs/v3.19.x/TypeScript#fastifyfastifyrequestrawserver-rawrequest-requestgeneric
[FastifyRequestGenericInterface]: /docs/v3.19.x/TypeScript#fastifyrequestgenericinterface
[RawRequestDefaultExpression]: /docs/v3.19.x/TypeScript#fastifyrawrequestdefaultexpressionrawserver
[FastifyReply]: /docs/v3.19.x/TypeScript#fastifyfastifyreplyrawserver-rawreply-contextconfig
[RawReplyDefaultExpression]: /docs/v3.19.x/TypeScript#fastifyrawreplydefaultexpression
[FastifyServerOptions]: /docs/v3.19.x/TypeScript#fastifyfastifyserveroptions-rawserver-logger
[FastifyInstance]: /docs/v3.19.x/TypeScript#fastifyfastifyinstance
[FastifyLoggerOptions]: /docs/v3.19.x/TypeScript#fastifyfastifyloggeroptions
[ContextConfigGeneric]: /docs/v3.19.x/TypeScript#ContextConfigGeneric
[FastifyPlugin]: ##fastifyfastifypluginoptions-rawserver-rawrequest-requestgeneric
[FastifyPluginCallback]: /docs/v3.19.x/TypeScript#fastifyfastifyplugincallbackoptions
[FastifyPluginAsync]: /docs/v3.19.x/TypeScript#fastifyfastifypluginasyncoptions
[FastifyPluginOptions]: /docs/v3.19.x/TypeScript#fastifyfastifypluginoptions
[FastifyRegister]: /docs/v3.19.x/TypeScript#fastifyfastifyregisterrawserver-rawrequest-requestgenericplugin-fastifyplugin-opts-fastifyregisteroptions
[FastifyRegisterOptions]: /docs/v3.19.x/TypeScript#fastifyfastifytregisteroptions
[LogLevel]: /docs/v3.19.x/TypeScript#fastifyloglevel
[FastifyError]: /docs/v3.19.x/TypeScript#fastifyfastifyerror
[RouteOptions]: /docs/v3.19.x/TypeScript#fastifyrouteoptionsrawserver-rawrequest-rawreply-requestgeneric-contextconfig
```

**Comment by jsumners** [comment]
@luisorbaiceta this seems to be working:

TypeScript - Vivaldi 2021-12-12 14-42-25

**Comment by luisorbaiceta** [comment]
The remapping should remove de `.md` extension from the files.

image

**Comment by jsumners** [comment]
Please add a review suggestion. I will not be able to get back to this directly for a while.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by luisorbaiceta — APPROVED** [review]

**Pull request merged**
