### PR TITLE
Added Satiurn Logo

### PR DESCRIPTION
**Pull request by FrancescoMasaia**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
The svg is not correct, CI is failing with:

> invalid SVG content, missing "width" or "height" attribute in xmlns tag

**Comment by FrancescoMasaia** [comment]
Thank you, I've just corrected it.

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Eomm — APPROVED** [review]

**Pull request merged**
