### PR TITLE
Adds HospitalRun to organisations

### PR DESCRIPTION
**Pull request by fox1t**
Adds HospitalRun to organisations

#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Eomm — APPROVED** [review]
:tada:

**Review by mcollina — APPROVED** [review]
lgtm

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by lmammino** [comment]
Great stuff, thanks @fox1t

**Comment by fox1t** [comment]
@lmammino Thanks! Lets spread our love for Fastify! ;)

**Pull request merged**
