### PR TITLE
Fixes website build preview on Windows

### LINKED ISSUE #240: Run local site on Windows
On win bad thinks are happening.

There is a [workaround](https://github.com/fastify/website/pull/143#issuecomment-573112072):

In the `src\scripts\buildWebsite.js` file change the script:

https://github.com/fastify/website/blob/97ff86e9d1a1aa8d100a5f33e01cc5c8be59ed69/src/scripts/buildWebsite.js#L75-L77

To:

```
  .use(
    function (files, ms, done) {
      var metadata = ms.metadata()
      metadata.hashes = metadata.hashes || {}
      var relevantFiles = Object.keys(files)
      relevantFiles.forEach(function (filepath) {
        metadata.hashes[filepath.replace(/\\/ig, '/')] = filepath
      })
      return process.nextTick(done)
    }
  )
```

Or send a PR to [metalsmith-contenthash](https://github.com/ekytr/metalsmith-contenthash#readme)

> 
> The easiest way to test your changes is to do `npm run start:dev`. It should open a browser window for you. Every time you change a file it should rebuild and refresh automatically (with some lag 😅)
> 
> Let me know if this helps or if you get stuck with something

I do attempt to test the changes locally however the resources don't load 😞   :
Capture

The following errors are thrown in the console:

`The stylesheet http://127.0.0.1:8080/ was not loaded because its MIME type, “text/html”, is not “text/css”.`
`The script from “http://127.0.0.1:8080/” was loaded even though its MIME type (“text/html”) is not a valid JavaScript MIME type.`

Tested using both Edge 88.0.705.68 and Firefox 85.0.2

_Originally posted by @Fdawgs in https://github.com/fastify/website/issues/238#issuecomment-780442720_

### PR DESCRIPTION
**Pull request by lmammino**
This change should close the issue reported in #240.

I had a bit of trouble replicating the issue (since I am on a mac), @Eomm, @Fdawgs could you please pull this branch and see if it fixes the issue for you?

Thank you :)

Closes #240.

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by RafaelGSS — COMMENTED** [review]
LGTM.

**Comment by RafaelGSS** [comment]
Note: I don't use windows to validate as well.

**Comment by lmammino** [comment]
@mcollina did you try on windows?

**Comment by Fdawgs** [comment]
No change for me unfortunately @lmammino, still the same. 😢

**Comment by lmammino** [comment]
Thanks a lot anyway, @Fdawgs! 

@Eomm, I tried to apply your suggested solution from #240, but I am not sure I understand what's the real problem here. Could you argument a bit more about what did you try and why you think that solution should work? Maybe there's something small we are missing...

I might be able to get my hands on a Windows machine at some point next week and maybe try to investigate things there...

**Comment by salesh** [comment]
Hey @lmammino as @Eomm mention

you left 
```
  .use(
    contenthash({
      pattern: ['**/*.{js,css,png,jpg,svg}']
    })
  )
```

This need to become 

```
  .use(
    function (files, ms, done) {
      const metadata = ms.metadata()
      metadata.hashes = metadata.hashes || {}
      const relevantFiles = Object.keys(files)
      relevantFiles.forEach(function (filepath) {
        metadata.hashes[filepath.replace(/\\/ig, '/')] = filepath
      })
      return process.nextTick(done)
    }
  )
```

Currently, you added the whole code after .use(contenthash.. and that's why it's not working.

Tested in on Windows 10 in Firefox/Edge and in Ubuntu Chrome/Firefox (just in case)

Screenshot from 2021-02-24 12-57-45

**Comment by lmammino** [comment]
That's interesting. Thanks, @salesh.

I am still not sure I understand the issue though.

If we remove the `contenthash` middleware, the file names won't contain hashes anymore (at least on mac). We need to have hashes for the final build. We use a CDN in production and without hashes the various resources will be cached for an indeterminate amount of time and we won't be able to get a swift refresh on new deployments...

I wonder if it's just `contenthash` that has an inconsistent behaviour between windows and mac/linux... maybe we should try to address that inconsistency...

**Comment by salesh** [comment]
> That's interesting. Thanks, @salesh.
> 
> I am still not sure I understand the issue though.
> 
> If we remove the `contenthash` middleware, the file names won't contain hashes anymore (at least on mac). We need to have hashes for the final build. We use a CDN in production and without hashes the various resources will be cached for an indeterminate amount of time and we won't be able to get a swift refresh on new deployments...
> 
> I wonder if it's just `contenthash` that has an inconsistent behaviour between windows and mac/linux... maybe we should try to address that inconsistency...

Hmm, I understand, totally forgot about that part...The scary part is -> the repository hasn't been changed for 4 years and can we even reach somebody?... :/ 

https://github.com/ekytr/metalsmith-contenthash/blob/master/index.js

So from what I can see from the code, we are missing that hashing part in our code

```
            var hash = crypto.createHash(options.algorithm);
            
            hash.update(files[filepath].contents);
            var digest = hash.digest('hex');
            
            var destination = options.rename(filepath, digest);
```


Sad thing is that the fix would probably just be changing this https://github.com/ekytr/metalsmith-contenthash/blob/f87353071649621363c68acb5131acbbdee98513/index.js#L53
```
          metadata.hashes[filepath] = destination;
```

into 

```
           metadata.hashes[filepath.replace(/\\/ig, '/')] = destination;
```

Because I believe backslash is the only issue here..

I saw that Manuel opened an issue https://github.com/ekytr/metalsmith-contenthash/issues/1 
Alternatives?
- ugly dev/prod or Windows only hack?
- implementing our own contenthash?

Not sure..

**Comment by Eomm** [comment]
The @salesh code [here](https://github.com/fastify/website/pull/241#issuecomment-785026682) works for me as well.

> Alternatives?

I would just ad an `if (process.platform === "win32")` to return the custom function or the `contenthash` one: this would cover the build pipe (that is not win) and the devs out there that would like to test the build locally.

The nicer would be to revamp the metalsmith, but it would take an extra effort (for me) - we could send a PR if the maintainer would like to release it

**Comment by Eomm** [comment]
Friendly ping @lmammino

**Comment by luisorbaiceta** [comment]
Hi everyone, I took over this and have found a fix for the contenthash plugin. I will send a PR

**Comment by lmammino** [comment]
Closed in favour of #263

**Pull request closed without merging**
