### PR TITLE
Encourage contributions with good first issues

### PR DESCRIPTION
**Pull request by lmammino**
These (Work In Progress) PR aims to add a new page where we can list all the "good first issues" in all the official Fastify repos to encourage new contributors to take part in the project.

The idea is to make API calls client-side to the GitHub APIs once the page loads. The idea is coming from [GlenTiki/gh-issue-finder](https://github.com/GlenTiki/gh-issue-finder) by @GlenTiki

## PREVIEW

🖼 https://exciting-cable.surge.sh/contribute/
🖼 https://nifty-mind.surge.sh/contribute/ (OLD)

## Todo list:

 - [X] Create new page
 - [X] Add link to the new contribute page in the nav bar
 - [x] Define catchy paragraph to encourage contributions (@mcollina & @delvedor, I might need your help here, maybe we can reuse something we already have in our code of conduct or similar docs)
 - [x] Add client side logic for fetching the issues (@GlenTiki I might love your help here)
 - [x] Styling

## Screenshots

Current new page.

Screen Shot 2020-01-30 at 4 51 50 PM

Highlights of new elements and things to figure out:

Screen Shot 2020-01-30 at 4 51 54 PM

### CODE REVIEW

**Comment by jsumners** [comment]
👍

**Comment by GlenTiki** [comment]
My merged work has a live preview here: https://objective-swanson-418266.netlify.com/contribute/

I wrote the text and styled as I found appropriate, please update as needed!

**Comment by jsumners** [comment]
I can see that page getting really long. Especially if we go add a bunch of issues to get v3 shipped.

**Comment by lmammino** [comment]
Good point @jsumners 

I was thinking to add groups based on the repository. Maybe we can add some filtering as well. I'll try to play with this idea and see if it helps.

**Comment by lmammino** [comment]
Did some progress on the styling. I'll try to add filtering buttons on top of the "cards" based on sub-projects (e.g. "fastify", "fastify-cli", etc...)

sneaky (STATIC 😕) preview 👍 

127 0 0 1_8080_contribute_

**Comment by GlenTiki** [comment]
@lmammino let me take a look at the API for the find issues req and see if I can expose some filtering based on repo, and add the repo to the returned json.

I'll add some docs for that endpoint in the repo too

**Comment by lmammino** [comment]
That would be cool 😎 . For now, I did some crappy regex-based extrapolation from the issue URL, not the cleanest, but good enough for the current prototyping!

**Comment by lmammino** [comment]
On second thought, regarding the filtering, I am not sure it's really worth it to do server-side filtering, because that will also mean that we will need to re-issue a new request every time a filter is turned on or off.

I would expect the number of total items to be reasonably small (in the order of hundreds at worst), so we should be able to do dynamic client-side filtering without issues. Thoughts?

**Comment by lmammino** [comment]
Regarding exposing the project in the API, that's still valuable. It would be great to have something in this shape:

```json
{ 
  "project": {
     "name": "fastify-cli",
     "url": "https://github.com/fastify/fastify-cli"
  }
}
```

**Comment by GlenTiki** [comment]
Keeping it client side is good for me! I'll still expose the repo in the
json to save yourself the regex check 😄

**Comment by GlenTiki** [comment]
Exposed some more data now. :) See: https://gh-issue-finder.now.sh/api/findIssues?org=fastify

**Comment by lmammino** [comment]
Preview available here: https://nifty-mind.surge.sh/contribute/

Let me know what you think :)

**Review by mcollina — APPROVED** [review]
lgtm

**Review by delvedor — COMMENTED** [review]
Great work!!
I'm not sure it makes sense to have the picture of the person who has created the issues, one might think that the issue has already been assigned. What do you think?

Speaking of assigned, is this feature aware of assigned issues? We should not show good first issues that have already been assigned.

**Review by jsumners — APPROVED** [review]
LGTM with @delvedor's feedback addressed. 

Also, a future PR to easily de-select all selected items would be nice. But definitely not a blocker for release.

**Comment by lmammino** [comment]
Feedback taken. I do like the avatars, but it can indeed be misleading. I was also thinking of a different design using checkboxes to make more obvious that those are filters. Let me see if I can turn this idea around quickly :)

**Comment by lmammino** [comment]
Hello folks!

New design available here: https://exciting-cable.surge.sh/contribute/

What do you think? :)

**Comment by jsumners** [comment]
image

**Comment by lmammino** [comment]
I hope that's not a Titanic @jsumners 😂

@delvedor, opinions?

**Review by delvedor — APPROVED** [review]
Lovely

**Review by SerayaEryn — APPROVED** [review]

**Pull request merged**
