### PR TITLE
Changed Copyright info in README

### PR DESCRIPTION
**Pull request by lmammino**
Sorry, I didn't notice before that this was attributed only to Me 😓

### CODE REVIEW

**Review by sinchang — CHANGES_REQUESTED** [review]
should update license file same

**Review by delvedor — APPROVED** [review]
No worries :P

**Comment by lmammino** [comment]
Thanks @sinchang, updated that as well now :P

**Review by mcollina — APPROVED** [review]
LGTM

**Review by sinchang — APPROVED** [review]

**Pull request merged**
