### PR TITLE
Fix Documentation overflow on menu links

### PR DESCRIPTION
**Pull request by lmammino**
See changes from left (current version) to right (fixes)

Screenshot 2019-07-21 at 15 53 58

### CODE REVIEW

**Review by allevo — COMMENTED** [review]
is there a popup (on hover event) that suggest the entire string?

**Comment by lmammino** [comment]
@allevo yes, through the `title` attribute on the `a` tags.

**Comment by mcollina** [comment]
+1 for a tooltip that displays the full name

**Comment by lmammino** [comment]
@mcollina is there already :)

**Review by mcollina — APPROVED** [review]
LGTM

**Review by allevo — APPROVED** [review]
LGTM

**Pull request merged**
