### PR TITLE
Add typescript shoutout to homepage (fixes #114)

### LINKED ISSUE #114: Mention TypeScript support our front page
We work hard on supporting TypeScript, we should reflect this on the front page of the site so devs know that we are a Node.js API Framework with TypeScript support.

### PR DESCRIPTION
**Pull request by GlenTiki**
See here for a preview: https://hungry-tereshkova-3ee959.netlify.com/

I've just robbed the docs on typescript for the basic section

### CODE REVIEW

**Comment by mcollina** [comment]
The async/await switch does not work.

**Comment by GlenTiki** [comment]
It working here for me,but it jumps when using it.will fix

**Comment by GlenTiki** [comment]
Updated based on feedback, updated Netlify deployment

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Ethan-Arrowood — APPROVED** [review]
Looks great! We should make note to update this section with v3 example when those docs are finished a live

**Review by lmammino — APPROVED** [review]
Sorry, a little bit late to the party here.

I think this is a great addition. Thanks @GlenTiki!

The only thing that I am worried about is that the home becomes a little bit too long this way, maybe making the _Core features_ a little bit harder to reach.

This is not a blocker for now, but more of a consideration. We should revisit design of the home at some point to make sure we have a clear and concise message. Thoughts?

**Comment by lmammino** [comment]
BTW, one simple win here could be to move the _Core features_ section before the quick start...

**Comment by GlenTiki** [comment]
Feedback applied @lmammino, let's add a follow-on issue when this gets merged, to redesign/breakdown the homepage. Updated my live preview.

**Comment by lmammino** [comment]
I love it! thanks @GlenTiki 

Shall we merge?

**Comment by GlenTiki** [comment]
I'm happy for it to be merged 👍

**Pull request merged**
