### PR TITLE
Updated team and acknowledgements sections

### LINKED ISSUE #33: Update team section
The website should reflect the new README in the main repo.

This requires changing the `src/website/data/team.yml` data file and the `src/website/layouts/home.html` template.

Ideally, we should respect the division between **lead maintainers** and **contributors** as in the main repo.

### PR DESCRIPTION
**Pull request by lmammino**
This is a preview of the new team section on the website as implemented by this PR:

screen shot 2017-10-11 at 23 50 33

Notice that also the acknowledgements section has been slightly  changed and now there's an explicit mention of the full community (with a link to the list of contributors on GitHub)

Closes #33

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
LGTM

I think the contributors list should be alphabetized upstream.

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by lmammino** [comment]
Good point @jsumners, i'll see if it's something easy to add directly in the template. Even though we are not applying upstream sorting anywhere else (ecosystem, benchmark, etc.) So this change might be slightly inconsistent. Thoughts?

**Comment by mcollina** [comment]
Let's start doing it for contributors. That's a fair way of listing them.

**Comment by mcollina** [comment]
This should be noted somewhere in the page as well.

**Comment by lmammino** [comment]
Cool @mcollina. I'll do the necessary changes ASAP.

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by lmammino** [comment]
Turns out that nunjuks has already an handy `sort` filter that can even sort by property. So the change was easier than expected.

Only caveat is that @cagataycali has been moved from the first to the last position... I guess having special chars in your name is more an issue than an advantage 😝 

@mcollina @jsumners let me know if this is good to merge now.

**Comment by lmammino** [comment]
Also added "In alphabetical order".

This is the final look at the moment:

screen shot 2017-10-12 at 09 32 48

**Comment by jsumners** [comment]
I meant they should be sorted in the original readme so that they would automatically be sorted here. I'll try to find some time to submit a PR today.

**Comment by lmammino** [comment]
Ooops, totally misunderstood! The issue is that at the moment the data is not taken from the original fastify readme. We should probably do that if we envision the team will change a lot in the future

**Comment by jsumners** [comment]
I see. I missed that in my initial review.

**Pull request merged**
