### PR TITLE
added new organization (MarsX)

### PR DESCRIPTION
**Pull request by alexanderisora**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by Fdawgs — CHANGES_REQUESTED** [review]
To be consistent with the other logos, can you name the file marsx or mars-x, please? Doesn't need the trailing `_logo` 😊

**Review by luisorbaiceta — APPROVED** [review]
👌

**Review by alexanderisora — COMMENTED** [review]
I renamed the file to "marsx".

**Review by Fdawgs — APPROVED** [review]

**Comment by luisorbaiceta** [comment]
Thanks!

**Pull request merged**
