### PR TITLE
Add Future Foundry to Organisations

### PR DESCRIPTION
**Pull request by essn**
Started using Fastify on client projects and LOVE it 😄 

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by mcollina — APPROVED** [review]
lgtm

**Review by jsumners — CHANGES_REQUESTED** [review]
Why does this SVG include a bunch of inlined JavaScript?

**Comment by mcollina** [comment]
Oooh that's nice.

**Review by mcollina — CHANGES_REQUESTED** [review]
remove the javascript

**Comment by essn** [comment]
Ah, my mistake. Our normal logo is white and would have appeared faded. That must've been added by the software I used to color it. Removed!

**Review by jsumners — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Review by lmammino — APPROVED** [review]

**Comment by lmammino** [comment]
Looks good, thanks @essn

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by lmammino** [comment]
@essn, just be careful that, at first glance, the JS you removed looks like geo-tracking code. I am not sure you might want to run that anywhere...

**Comment by essn** [comment]
@lmammino Yeah, definitely. It was a late-night push and I missed it. I'm glad you guys caught it. It is not a standard procedure on our end to include that script with our SVGs and this particular SVG conversion was a one-off. I am not a design guy, and after struggling with GIMP for a bit I turned to online tools.

Reading through the script for my own curiosity, and honestly, not exactly sure what the purpose of it is other than to track the location in a browser variable. Perhaps it opens up the possibility for XXS?

Anyways, I promise I'm not trying to hack ya'll, just show my support! 😬 

https://boxy-svg.com/ is the service I used.

**Comment by essn** [comment]
@lmammino this might be ancient history by now, but it worried me that my downloads had an unknown script in them. After some investigation, it looks like the ExpressVPN browser extension injected it. Unsure why, but that's a mystery for another day.

https://github.com/expressvpn/expressvpn_browser_extension/blob/5b20ddf774a9ffd8e754da176184653778f5a178/source/scripts/content/gps.js

Apologies for allowing that into the PR and that ya'll had to catch it. Thank you for the review, though, and for the wonderful (and fast!) webserver 🙂

**Pull request merged**
