### PR TITLE
Improve clarification in home page

### PR DESCRIPTION
**Pull request by danielgospodinow**
I propose improved clarification in some sentences on the website's home page.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by Fdawgs — CHANGES_REQUESTED** [review]
Could be compressed down to the following:

> Enter Fastify. Fastify is a web framework highly focused on providing the best developer experience with the least overhead and a powerful plugin architecture, inspired by Hapi and Express. As far as we know, it is one of the fastest web frameworks in town.

**Comment by danielgospodinow** [comment]
> Could be compressed down to the following:
> 
> > Enter Fastify. Fastify is a web framework highly focused on providing the best developer experience with the least overhead and a powerful plugin architecture, inspired by Hapi and Express. As far as we know, it is one of the fastest web frameworks in town.

It sounds wonderful! Should I introduce those changes?

**Review by luisorbaiceta — APPROVED** [review]
Lgtm

**Review by jsumners — APPROVED** [review]

**Review by Fdawgs — APPROVED** [review]

**Review by RafaelGSS — APPROVED** [review]
LGTM.

**Pull request merged**
