### PR TITLE
Fix links color for accessibility and updates to bulma 0.8

### LINKED ISSUE #136: Links green color contrast ratio is very low
## 🐛 Bug Report
Links green colour contrast ratio doesn't meet WCAG guidelines, and it's really burning my eyes. [Color Contrast Checker](https://webaim.org/resources/contrastchecker/?fcolor=00D1B2&bcolor=FFFFFF)

Screenshot 2019-10-24 at 10 47 44

## To Reproduce

Screenshot 2019-10-24 at 10 52 22

## Expected behavior

Colour contrast ratio must be at least 4.5:1 or more. Darkening the green color to `#008571` pass the guidelines and looks much better for me.

Screenshot 2019-10-24 at 10 56 12

Screenshot 2019-10-24 at 10 54 39

Happy to help with the issue if you guys don't mind the new color.

### PR DESCRIPTION
**Pull request by lmammino**
Fixes #136 

It also updates Bulma to the latest version (0.8).

I created a preview here: https://fastify-io-fix-links-color-for-accessibility.surge.sh/

Please help me to ensure that everything is still looking good as Bulma has some small breaking changes.

### CODE REVIEW

**Comment by mshaaban0** [comment]
looks good to me 👍

**Review by Eomm — APPROVED** [review]

**Comment by lmammino** [comment]
@Eomm is this ok to be merged with just 1 :+1:? Should we wait for more reviewers? :)

**Comment by Eomm** [comment]
We should wait for at least another approval 🙏🏼

**Comment by Ethan-Arrowood** [comment]
I ran this through Lighthouse and it is returning the links are still failing the accessibility test (see screenshot below)
Screen Shot 2019-11-04 at 2 40 23 PM

**Comment by Ethan-Arrowood** [comment]
Based on WebAIM (https://webaim.org/resources/contrastchecker/?fcolor=008571&bcolor=FFFFFF) it looks like it needs to be slightly darker.

**Comment by lmammino** [comment]
Thanks @Ethan-Arrowood, I'll make the changes and test again with webaim :)

**Comment by lmammino** [comment]
It should be fixed now.

The remaining issues are with the code highlighter. I can look into another theme with better contrast in a separate PR

Screenshot 2019-11-06 at 20 33 38

**Comment by Ethan-Arrowood** [comment]
LGTM now 👍 great work! I always love a11y changes ❤️

**Review by Ethan-Arrowood — APPROVED** [review]

**Comment by lmammino** [comment]
@Eomm did you remove your approval? 😛

**Review by Eomm — APPROVED** [review]
Nope, I think new commit + request review deleted it!

**Review by SerayaEryn — APPROVED** [review]
LGTM

**Pull request merged**
