### PR TITLE
add openjs in license

### PR DESCRIPTION
**Pull request by Eomm**
- [x] Update legal copyright notice on project website and github

Refs:
https://github.com/openjs-foundation/project-onboarding/issues/35
https://github.com/fastify/fastify/pull/2039

### CODE REVIEW

**Review by delvedor — APPROVED** [review]
LGTM

**Comment by Eomm** [comment]
⚡ I saw right now this open PR
https://github.com/openjs-foundation/cross-project-council/pull/414/files
that suggest a more wide footer.

I will wait for it before update this PR accordingly

**Review by lmammino — APPROVED** [review]
Purely from an aesthetic perspective, it looks good to me.

Why are you thinking about a larger footer?

**Comment by lmammino** [comment]
Also, I took the freedom to make the current year variable, so we don't have to keep updating the footer in the future. Let me know if that's ok by you!

**Comment by Eomm** [comment]
No problem 👍🏼

The PR that is in review by the openjs council, suggests to add also links to cookie policy, privacy policy and many others terms of usage.

There are some pending comments in that pr, so I will check their final decision

**Comment by mcollina** [comment]
Side note, we should put in place a cookie and privacy policies. Maybe we can ask the Foundation for guidance.

**Review by SerayaEryn — APPROVED** [review]

**Comment by lmammino** [comment]
@mcollina, can we merge this or do you wish to wait for the cookie and privacy policy to be added?

**Comment by mcollina** [comment]
THis can land.

**Pull request merged**
