### PR TITLE
Please add OracleAPEXConsultant to organisations.

### PR DESCRIPTION
**Pull request by apexconsultant**
#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
This looks to be a PNG, not an actual SVG.

**Comment by lmammino** [comment]
Hello @apexconsultant and thanks for submitting this PR.

I second what @jsumners already mention. Please make sure the logo contains actual vector shapes and not raw pixels. This allows us to keep the logo consistent and well visible across multiple resolutions / devices.

Other than that, I am quite curious to understand more about how do you use Fastify. From the outside, it seems that the company is purely focused on "Oracle APEX".

Would you be able to share with us a case study where you used Fastify for one of your projects and why you didn't go with Apex?

**Comment by mcollina** [comment]
I'm not sure we can list the term "Oracle Apex" as it is a registered trademark.

**Comment by apexconsultant** [comment]
Hello All,

We will add a pure SVG logo, apologize for the wrong format generated/converted by the software.

@lmammino, we are promoting apex for the development of the data-centric web solutions, but along with that also dealing/utilizing other development platforms [ open source, Javascript, Java, PHP, .Net, NodeJs, React, Mobile development, etc.] also for meeting customers needs. You can check on https://www.oracleapexconsultant.com/services/development, here as we mentioned for the micro-services & web services development we are using the Fastify framework. To mention a very recent use case for one of the projects, we used MySQL as a database and on top of that leverages the power of NodeJs + Fastify for developing REST web-services which can be consumed by any end client - mobile apps & web apps. There are certain projects where we have to use a database other than oracle and the need for NodeJs for developing microservices. 

@mcollina, I would like to mention Oracle is the trademark, not Oracle APEX, and our company name is the OracleAPEXConsultant - single word. We are not using the same color, shape, or fonts as per the trademark guidelines. We have been listed on the oracle official community section as a consulting company, since 2011.  Please check it out - https://apex.oracle.com/pls/apex/apex_pm/r/apex-community/consulting-companies. We've initiated a request for the updating logo, and that will be addressed soon, after the company new year holiday. 

Please let us know in case of any questions.

**Thanks & Regards,**
Team OAC

**Review by mcollina — APPROVED** [review]
lgtm! Thanks for the full explanation!

**Comment by lmammino** [comment]
Thank you @apexconsultant for taking the time to answer our queries. I think at this point the only blocker is to get the updated SVG and then we could probably get this shipped :)

**Comment by mcollina** [comment]
Please send a fresh PR with updated logo

**Pull request merged**
