### PR TITLE
update home page to use preHandler

### PR DESCRIPTION
**Pull request by juanprq**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows [Code of conduct](https://github.com/fastify/fastify/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Review by jsumners — APPROVED** [review]
LGTM

Thank you for finding and fixing this.

**Review by mcollina — APPROVED** [review]
Thanks!

**Comment by juanprq** [comment]
I don't know what happens with the build step in the CI, could you guys give me a hand with that? I did saw a 500 error on the trace, maybe re-running the pipeline?

**Review by delvedor — APPROVED** [review]
LGTM

cc @lmammino

**Comment by lmammino** [comment]
Sorry for the delay. It seemed like a glitch with GitHub APIS. Merging this :)
Thanks @juanprq !

**Review by lmammino — APPROVED** [review]

**Pull request merged**
