### PR TITLE
Add typescript ref to home page

### PR DESCRIPTION
**Pull request by Ethan-Arrowood**
As title suggests, adding a TypeScript reference to the homepage.

### CODE REVIEW

**Review by jsumners — COMMENTED** [review]
The TS support policy has been one of letting the community provide it. To me, this says TS is a core feature of Fastify and I do not think it is.

**Comment by Ethan-Arrowood** [comment]
True, in my mind I just wanna be like 'We support TypeScript too!' but that doesn't read well with the opening text. I'll think more on the wording tomorrow and see what I can come up with.

**Comment by mcollina** [comment]
Maybe we can add this into the features list. It’s probably better to update that in the README first, and then update it here. It would have more visibility and discussion.

**Comment by delvedor** [comment]
> Maybe we can add this into the features list. It’s probably better to update that in the README first, and then update it here. It would have more visibility and discussion.

👍

**Comment by Ethan-Arrowood** [comment]
The Features section would be a great spot for this! I’ll make sure to add it there.

**Review by delvedor — APPROVED** [review]
LGTM

**Review by mcollina — APPROVED** [review]
LGTM

**Comment by Ethan-Arrowood** [comment]
Thanks! Merging now

**Pull request merged**
