### PR TITLE
Fix broken links

### PR DESCRIPTION
**Pull request by luisorbaiceta**
Due to some reports about broken links, I'm opening this PR to detect all the edge cases that were not covered by the previous website and fix current reports.

### Broken Links list:

- [x] [website](https://github.com/fastify/fastify/blob/627f7bde9a5d483f68b765668ea4fe964ab41cbf/docs/Reference/Encapsulation.md?plain=1#L8)
- [x] [website](https://github.com/fastify/fastify/blob/627f7bde9a5d483f68b765668ea4fe964ab41cbf/docs/Reference/Hooks.md?plain=1#L39)
- [x] Missing encapsulation `svg`
- [x] [website](https://github.com/fastify/fastify/blob/627f7bde9a5d483f68b765668ea4fe964ab41cbf/docs/Reference/Middleware.md?plain=1#L44)

- docs: needs to be fixed in fastify/fastify
- web: needs to be fixed in fastify/website

#### Checklist

- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by luisorbaiceta** [comment]
@jsumners seems that previous links like `/docs/foo/bar` were 404s in the previous website too due to wrong version remapping. I'll do my best to find any possible missing edge case or link type but would really appreciate a hand on this. There are *SOO*  many link types

**Comment by jsumners** [comment]
> There are _SOO_ many link types

I refer you back to my original comment -- https://github.com/fastify/fastify/pull/3474#issue-1060766581

I'm really not happy with the current way our site is generated. It was a really valiant effort to keep as many versions as possible on the site, but it doesn't scale and is very unmaintainable.

**Comment by luisorbaiceta** [comment]
Agree, however my concern will be to try to fix this as I really don't know the [status](https://github.com/fastify/website-next/issues/11#issue-1080035137) of new site.

**Comment by luisorbaiceta** [comment]
@jsumners please check the list above, I will document all the broken links

**Comment by luisorbaiceta** [comment]
Website links have been fix. I will migrate the fastify/fastify part to that repo and open a separate PR so we can keep track from there. Let's wait to merge this till I have fixed that so I can check that ALL the links are correct in dev.

**Comment by luisorbaiceta** [comment]
**Every single link checked**

**Review by mcollina — APPROVED** [review]
k lgtm

**Comment by jsumners** [comment]
> **Every single link checked**

tenor

**Review by jsumners — APPROVED** [review]

**Pull request merged**
