### PR TITLE
feat(organisations): add habit to organisations

### PR DESCRIPTION
**Pull request by RafaelGSS**
#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [X] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by RafaelGSS** [comment]
The CI failing seems non-related to the PR.

**Comment by lmammino** [comment]
Hello @RafaelGSS.

Just be aware that you have a lot of white space around the actual logo in the canvas. This will make it so that once rendered in the page, the logo would be quite small...

I'd recommend cutting the canvas to something like the orange rectangle in this picture:

Screenshot 2021-02-15 at 14 39 35

**Comment by RafaelGSS** [comment]
@lmammino Looking on it, thanks.

**Comment by RafaelGSS** [comment]
Fixed @lmammino. The CI broke is not related to this feature, it's?

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by lmammino** [comment]
Looking into the CI failure... it does not seem related...

**Comment by lmammino** [comment]
The branch was behind current master where the error was already resolved.

🤞 now the CI will go green!

**Comment by lmammino** [comment]
YAY worked

**Review by lmammino — APPROVED** [review]

**Pull request merged**
