### PR TITLE
feat: `bestgameprice` and `enucuzoyun` logos

### PR DESCRIPTION
**Pull request by hsynlms**
We proudly use Fastify in both projects.

#### Checklist

- [x] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

### CODE REVIEW

**Comment by mcollina** [comment]
@luisorbaiceta could you check why the netlify build is failing?

**Comment by luisorbaiceta** [comment]
@hsynlms could you rebase?

**Review by Fdawgs — CHANGES_REQUESTED** [review]
These are the same site, but with one localized in Turkish.
I think only one should be added, but not both.

Alternatively, listing the actually organisation behind the sites (23 Studios) may be better? As this is a list of organisations.

**Comment by hsynlms** [comment]
Actually, both websites have different environments but the same theming. 23 Studios is our partner and the investor.

But if you say so, I can keep only Bestgameprice logo. Because it's for global. Enucuzoyun is only for the Turkey market.

**Review by luisorbaiceta — APPROVED** [review]

**Review by Fdawgs — APPROVED** [review]

**Pull request merged**
